import { type NextPage } from "next";
import Head from "next/head";

import Banner from "../components/Banner";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Banner imagePath="/images/bag-pipes.jpg" title="Welcome" />
        <div className="mt-4 flex h-full flex-1 flex-col items-center justify-around space-x-4  md:flex-row">
          <div className="m-2 min-h-[20rem] w-[20rem]  rounded-md border-2 border-solid border-gray-300 p-4">
            Card 1
          </div>
          <div className="m-2 min-h-[20rem] w-[20rem]  rounded-md border-2 border-solid border-gray-300 p-4">
            Card 2
          </div>
          <div className="m-2 min-h-[20rem] w-[20rem]  rounded-md border-2 border-solid border-gray-300 p-4">
            Card 3
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
